### ISSUE TITLE
Fix Cork Cellar ID format

### ISSUE THREAD

**Issue by cbrit** [PeggyJV/sommelier#129]
The agreed upon cellar_id format up to this point is of the format `chainname:address` (example: `ethereum:0x4C4a2f8c81640e47606d3fd77B353E87Ba015584`) but currently the cork module treats an ID as only the address. Steward currently requires IDs to be in this format. `0x4C4a2f8c81640e47606d3fd77B353E87Ba015584` can be approved by governance but the Steward cork submission will fail when steward checks for approval of `ethereum:0x4C4a2f8c81640e47606d3fd77B353E87Ba015584`. 

Opening this issue to document the need for a solution.

**Comment by EricBolten** [comment]
I think we landed on all addresses being Ethereum mainnet/testnet addresses for the time being until we ugprade to multi-EVM support, so closing this out.
