### ISSUE TITLE
Workflow from Send to Cosmos Event to Stop Loss

### ISSUE THREAD

**Issue by zmanian** [PeggyJV/sommelier#15]
The current Peg Zone smart contracts emit a SendToCosmos event when ERC 20 tokens are added to the bridge.

We need a flow from SendToCosmos event to stop loss initiated.

1. We need to validate that that the EthAddress of ERC20 token is a valid liquidity pool.

2. We need to capture the stop loss information for that pair_id/Etheraddress of the ERC20 token issue.

Should the validation of 1 be done in the consensus state machine?

Should we be trying to have an additional event in the contract to capture the stop loss information or should we capture this information in a metatransaction?

**Comment by jtremback** [comment]
I don't think it makes sense to overload sendToCosmos with this functionality. If we want to trigger actions on the cosmos side from an Ethereum wallet we should simply have another method that fires an event containing a user-supplied string and msg.sender. Then any command can be triggered on cosmos in reaction to this.

**Comment by jtremback** [comment]
So to trigger the stop loss stuff, a user would first use sendToCosmos to put their LP tokens into Gravity, then call the new method tell the cosmos chain to do the stop loss stuff

**Comment by zmanian** [comment]
this is similar to the metatransaction workflow and it saves having to spend gas on the main chain.

**Comment by jtremback** [comment]
We should sync up on the metatransaction workflow. We could also add a free form string to sendToCosmos I guess
