### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#33]
Add prometheus metrics for the oracle feeder. Some ideas:

- Last block height
- Successful transactions
- Successful graph queries

This will also allow easy setup for monitoring and alerting.

[Start metrics server in this function](https://github.com/PeggyJV/sommelier/blob/main/cmd/oracle-feeder/cmd/start.go#L41)
[Prometheus Docs](https://prometheus.io/docs/guides/go-application/)

**Comment by fedekunze** [comment]
would love to work on this
