### ISSUE TITLE
Add rebalance call ABI and test to allocation

### ISSUE THREAD

**Issue by jackzampolin** [PeggyJV/sommelier#41]
https://github.com/VolumeFi/cellars/blob/main/contracts/CellarPoolShare.sol#L491

**Comment by taariq** [comment]
@jackzampolin We can pack it as a tuple array.
https://docs.soliditylang.org/en/v0.7.6/abi-spec.html#handling-tuple-types. You good to go here or is more needed?

**Comment by webelf101** [comment]
`{
      "inputs": [
        {
          "components": [
            {
              "internalType": "uint184",
              "name": "tokenId",
              "type": "uint184"
            },
            {
              "internalType": "int24",
              "name": "tickUpper",
              "type": "int24"
            },
            {
              "internalType": "int24",
              "name": "tickLower",
              "type": "int24"
            },
            {
              "internalType": "uint24",
              "name": "weight",
              "type": "uint24"
            }
          ],
          "internalType": "struct ICellarPoolShare.CellarTickInfo[]",
          "name": "_cellarTickInfo",
          "type": "tuple[]"
        }
      ],
      "name": "rebalance",
      "outputs": [],
      "stateMutability": "nonpayable",
      "type": "function"
    }`

This is ABI of rebalance function. Is this enough?

**Comment by taariq** [comment]
@jackzampolin FYI. Let us know.
